### ISSUE TITLE
AUR package has a few issues

### ISSUE THREAD

**Issue by kseistrup** [deivshon/ifetch#2]
#### Main issue

When checking the newly built package with `namcap(1)`, this is what I see:

```sh
$ namcap ifetch-git-r135.d85f773-1-x86_64.pkg.tar.zst
ifetch-git W: ELF file ('usr/bin/ifetch') lacks FULL RELRO, check LDFLAGS.
ifetch-git E: Missing custom license directory (usr/share/licenses/ifetch-git)
```

As for the RELRO: The included `Makefile` doesn't take `$LDFLAGS` (possibly including `$LTOFLAGS`) into consideration, so that the binary will lack “FULL RELRO”.

Also, the Makefile completely ignores any `$CFLAGS` already present in the environment. I suggest using `?=` instead of `=` when assigning CFLAGS:

```Makefile
	CFLAGS ?= -Wall -Wextra -O2
```

----

#### Bonus issue

Since the program is MIT licensed, `LICENSE` ought to be copied to the `/usr/share/licenses/$pkgname/LICENSE` directory. This can easily be done in the `package()` function in the `PKGBUILD` file:

```bash
package() {
  cd "$pkgname"
  DEST_DIR="$pkgdir" make install
  install -Dm0644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
```

**Comment by deivshon** [comment]
Thank you for bringing up these issues! I pushed fixes here and on the AUR repo, everything should be solved now, feel free to reopen if you see any other problems!

**Comment by kseistrup** [comment]
Looks good! :)
