### ISSUE TITLE
Vertical alignment fails if separator is a multibyte character

### ISSUE THREAD

**Issue by kseistrup** [deivshon/ifetch#4]
I changed the separator in `ifetchrc` from `s=" >> "` to `s=" » "`, and this is what I saw:

![ifetch-alignment](https://user-images.githubusercontent.com/25586/222342625-508ace24-4285-4141-864f-e2ca2caf6bc4.png)

I assume `strlen(3)` thinks that ‘»’ is two characters wide, but “RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK” is a two-byte character with a width of 1.

I'm not an expert in these matters, but using `wcslen(3)` instead of `strlen(3)` could possibly solve this. However, it is not as simple as replacing all occurances of `strlen()` with `wcslen()` since some of the data structures are expecting a `char *` and `wcslen(3)` expects `wchar_t *`.

I don't really speak C, so I cannot provide a diff.

**Comment by deivshon** [comment]
Multibyte characters should not cause issues now! Let me know if anything doesn't work as expected

**Comment by kseistrup** [comment]
That was way more changes than I had expected. No wonder it didn't work just by replacing `strlen()` with `wcslen()`. :wink:
