### ISSUE TITLE
Enhancement request: Perhaps lose adornments if stdout is not a TTY?

### ISSUE THREAD

**Issue by kseistrup** [deivshon/ifetch#5]
When redirecting the output from `ifetch` to a file (or simple filtering through `cat(1)`), the output still contains ANSI colouring and boldness.

It could be useful if `ifetch` were producing unadorned text when standard output is not referring to a terminal. See `isatty(3)` for details.

**Comment by deivshon** [comment]
Agreed, it's a very reasonable change

**Comment by kseistrup** [comment]
That was fast — thanks!
