### ISSUE TITLE
AUR package: upgrade overwrites configuration files

### ISSUE THREAD

**Issue by kseistrup** [deivshon/ifetch#6]
As of `aur/ifetch-git r138.34bf52f-1` (and earlier), the system wide configuration files will be overwritten on each upgrade, discarding possible customisations.

As a minimum, `/etc/ifetch/ifetchrc` should be left untouched, and adding

```sh
backup=('etc/ifetch/ifetchrc')
```

to the `PKGBUILD` file will ensure that the configuration file that comes with the package will be installed as `ifetchrc.pacnew`:

```
:: Processing package changes…
(1/1) upgrading ifetch-git                                                                                                      [###########################################################] 100%
warning: /etc/ifetch/ifetchrc installed as /etc/ifetch/ifetchrc.pacnew
:: Running post-transaction hooks…
```

From there the user can assess if there are new options available that should be applied to the customised configuration file.

See `PKGBUILD(5)` for details.

**Comment by deivshon** [comment]
Thank you for bringing this up! The updated PKGBUILD has been pushed to the AUR
